/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Gm7DashboardRouteImport } from './routes/gm7-dashboard'
import { Route as HomeRouteImport } from './routes/home'
import { Route as MarketRouteImport } from './routes/market'
import { Route as SnnseiRouteImport } from './routes/snnsei'
import { Route as TournamentsRouteImport } from './routes/tournaments'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Gm7DashboardRoute = Gm7DashboardRouteImport.update({
  id: '/gm7-dashboard',
  path: '/gm7-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const SnnseiRoute = SnnseiRouteImport.update({
  id: '/snnsei',
  path: '/snnsei',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gm7-dashboard': typeof Gm7DashboardRoute
  '/home': typeof HomeRoute
  '/market': typeof MarketRoute
  '/snnsei': typeof SnnseiRoute
  '/tournaments': typeof TournamentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gm7-dashboard': typeof Gm7DashboardRoute
  '/home': typeof HomeRoute
  '/market': typeof MarketRoute
  '/snnsei': typeof SnnseiRoute
  '/tournaments': typeof TournamentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gm7-dashboard': typeof Gm7DashboardRoute
  '/home': typeof HomeRoute
  '/market': typeof MarketRoute
  '/snnsei': typeof SnnseiRoute
  '/tournaments': typeof TournamentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/gm7-dashboard' | '/home' | '/market' | '/snnsei' | '/tournaments'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gm7-dashboard' | '/home' | '/market' | '/snnsei' | '/tournaments'
  id:
    | '__root__'
    | '/'
    | '/gm7-dashboard'
    | '/home'
    | '/market'
    | '/snnsei'
    | '/tournaments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Gm7DashboardRoute: typeof Gm7DashboardRoute
  HomeRoute: typeof HomeRoute
  MarketRoute: typeof MarketRoute
  SnnseiRoute: typeof SnnseiRoute
  TournamentsRoute: typeof TournamentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gm7-dashboard': {
      id: '/gm7-dashboard'
      path: '/gm7-dashboard'
      fullPath: '/gm7-dashboard'
      preLoaderRoute: typeof Gm7DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snnsei': {
      id: '/snnsei'
      path: '/snnsei'
      fullPath: '/snnsei'
      preLoaderRoute: typeof SnnseiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Gm7DashboardRoute: Gm7DashboardRoute,
  HomeRoute: HomeRoute,
  MarketRoute: MarketRoute,
  SnnseiRoute: SnnseiRoute,
  TournamentsRoute: TournamentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
